/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiAgentStylesRouteImport } from './routes/api/agent-styles'
import { Route as ApiAppUpdateRouteImport } from './routes/api/app-update'
import { Route as ApiCacheWarmingRouteImport } from './routes/api/cache-warming'
import { Route as ApiDefaultCwdRouteImport } from './routes/api/default-cwd'
import { Route as ApiFileIndexRouteImport } from './routes/api/file-index'
import { Route as ApiHomeRouteImport } from './routes/api/home'
import { Route as ApiImageResizeRouteImport } from './routes/api/image-resize'
import { Route as ApiModelsRouteImport } from './routes/api/models'
import { Route as ApiModelsConfigRouteImport } from './routes/api/models-config'
import { Route as ApiPluginsRouteImport } from './routes/api/plugins'
import { Route as ApiProjectTrustRouteImport } from './routes/api/project-trust'
import { Route as ApiProjectsRouteImport } from './routes/api/projects'
import { Route as ApiRemoteAccessRouteImport } from './routes/api/remote-access'
import { Route as ApiSessionsRouteImport } from './routes/api/sessions'
import { Route as ApiSkillsRouteImport } from './routes/api/skills'
import { Route as ApiSubagentsRouteImport } from './routes/api/subagents'
import { Route as ApiUiLocaleRouteImport } from './routes/api/ui-locale'
import { Route as ApiWorktreesRouteImport } from './routes/api/worktrees'
import { Route as ApiAgentIdRouteImport } from './routes/api/agent/$id'
import { Route as ApiAgentNewRouteImport } from './routes/api/agent/new'
import { Route as ApiAgentRunningRouteImport } from './routes/api/agent/running'
import { Route as ApiAuthAllProvidersRouteImport } from './routes/api/auth/all-providers'
import { Route as ApiAuthProvidersRouteImport } from './routes/api/auth/providers'
import { Route as ApiCwdBrowseRouteImport } from './routes/api/cwd/browse'
import { Route as ApiCwdValidateRouteImport } from './routes/api/cwd/validate'
import { Route as ApiFilesSplatRouteImport } from './routes/api/files/$'
import { Route as ApiGitDiffRouteImport } from './routes/api/git/diff'
import { Route as ApiGitStatusRouteImport } from './routes/api/git/status'
import { Route as ApiLocalSplatRouteImport } from './routes/api/local/$'
import { Route as ApiModelsConfigCatalogRouteImport } from './routes/api/models-config/catalog'
import { Route as ApiModelsConfigDiscoverRouteImport } from './routes/api/models-config/discover'
import { Route as ApiModelsConfigTestRouteImport } from './routes/api/models-config/test'
import { Route as ApiModelsScopeRouteImport } from './routes/api/models/scope'
import { Route as ApiSessionsIdRouteImport } from './routes/api/sessions/$id'
import { Route as ApiSkillsCheckRouteImport } from './routes/api/skills/check'
import { Route as ApiSkillsInstallRouteImport } from './routes/api/skills/install'
import { Route as ApiSkillsSearchRouteImport } from './routes/api/skills/search'
import { Route as ApiSkillsUpdateRouteImport } from './routes/api/skills/update'
import { Route as ApiAgentIdBashOutputRouteImport } from './routes/api/agent/$id/bash-output'
import { Route as ApiAgentIdEventsRouteImport } from './routes/api/agent/$id/events'
import { Route as ApiAgentIdSubagentsRouteImport } from './routes/api/agent/$id/subagents'
import { Route as ApiAgentRunningEventsRouteImport } from './routes/api/agent/running/events'
import { Route as ApiAuthApiKeyProviderRouteImport } from './routes/api/auth/api-key/$provider'
import { Route as ApiAuthLoginProviderRouteImport } from './routes/api/auth/login/$provider'
import { Route as ApiAuthLogoutProviderRouteImport } from './routes/api/auth/logout/$provider'
import { Route as ApiProvidersProviderUsageRouteImport } from './routes/api/providers/$provider/usage'
import { Route as ApiSessionsIdAutoNameRouteImport } from './routes/api/sessions/$id/auto-name'
import { Route as ApiSessionsIdContextRouteImport } from './routes/api/sessions/$id/context'
import { Route as ApiSessionsIdExportRouteImport } from './routes/api/sessions/$id/export'
import { Route as ApiSessionsIdStateRouteImport } from './routes/api/sessions/$id/state'
import { Route as ApiSessionsIdEntriesEntryIdThinkingRouteImport } from './routes/api/sessions/$id/entries/$entryId/thinking'
import { Route as ApiSessionsIdEntriesEntryIdToolResultRouteImport } from './routes/api/sessions/$id/entries/$entryId/tool-result'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentStylesRoute = ApiAgentStylesRouteImport.update({
  id: '/api/agent-styles',
  path: '/api/agent-styles',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAppUpdateRoute = ApiAppUpdateRouteImport.update({
  id: '/api/app-update',
  path: '/api/app-update',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCacheWarmingRoute = ApiCacheWarmingRouteImport.update({
  id: '/api/cache-warming',
  path: '/api/cache-warming',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDefaultCwdRoute = ApiDefaultCwdRouteImport.update({
  id: '/api/default-cwd',
  path: '/api/default-cwd',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFileIndexRoute = ApiFileIndexRouteImport.update({
  id: '/api/file-index',
  path: '/api/file-index',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHomeRoute = ApiHomeRouteImport.update({
  id: '/api/home',
  path: '/api/home',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiImageResizeRoute = ApiImageResizeRouteImport.update({
  id: '/api/image-resize',
  path: '/api/image-resize',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiModelsRoute = ApiModelsRouteImport.update({
  id: '/api/models',
  path: '/api/models',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiModelsConfigRoute = ApiModelsConfigRouteImport.update({
  id: '/api/models-config',
  path: '/api/models-config',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPluginsRoute = ApiPluginsRouteImport.update({
  id: '/api/plugins',
  path: '/api/plugins',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProjectTrustRoute = ApiProjectTrustRouteImport.update({
  id: '/api/project-trust',
  path: '/api/project-trust',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProjectsRoute = ApiProjectsRouteImport.update({
  id: '/api/projects',
  path: '/api/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRemoteAccessRoute = ApiRemoteAccessRouteImport.update({
  id: '/api/remote-access',
  path: '/api/remote-access',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSessionsRoute = ApiSessionsRouteImport.update({
  id: '/api/sessions',
  path: '/api/sessions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSkillsRoute = ApiSkillsRouteImport.update({
  id: '/api/skills',
  path: '/api/skills',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSubagentsRoute = ApiSubagentsRouteImport.update({
  id: '/api/subagents',
  path: '/api/subagents',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUiLocaleRoute = ApiUiLocaleRouteImport.update({
  id: '/api/ui-locale',
  path: '/api/ui-locale',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWorktreesRoute = ApiWorktreesRouteImport.update({
  id: '/api/worktrees',
  path: '/api/worktrees',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentIdRoute = ApiAgentIdRouteImport.update({
  id: '/api/agent/$id',
  path: '/api/agent/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentNewRoute = ApiAgentNewRouteImport.update({
  id: '/api/agent/new',
  path: '/api/agent/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentRunningRoute = ApiAgentRunningRouteImport.update({
  id: '/api/agent/running',
  path: '/api/agent/running',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthAllProvidersRoute = ApiAuthAllProvidersRouteImport.update({
  id: '/api/auth/all-providers',
  path: '/api/auth/all-providers',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthProvidersRoute = ApiAuthProvidersRouteImport.update({
  id: '/api/auth/providers',
  path: '/api/auth/providers',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCwdBrowseRoute = ApiCwdBrowseRouteImport.update({
  id: '/api/cwd/browse',
  path: '/api/cwd/browse',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCwdValidateRoute = ApiCwdValidateRouteImport.update({
  id: '/api/cwd/validate',
  path: '/api/cwd/validate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFilesSplatRoute = ApiFilesSplatRouteImport.update({
  id: '/api/files/$',
  path: '/api/files/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGitDiffRoute = ApiGitDiffRouteImport.update({
  id: '/api/git/diff',
  path: '/api/git/diff',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGitStatusRoute = ApiGitStatusRouteImport.update({
  id: '/api/git/status',
  path: '/api/git/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLocalSplatRoute = ApiLocalSplatRouteImport.update({
  id: '/api/local/$',
  path: '/api/local/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiModelsConfigCatalogRoute = ApiModelsConfigCatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => ApiModelsConfigRoute,
} as any)
const ApiModelsConfigDiscoverRoute = ApiModelsConfigDiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => ApiModelsConfigRoute,
} as any)
const ApiModelsConfigTestRoute = ApiModelsConfigTestRouteImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => ApiModelsConfigRoute,
} as any)
const ApiModelsScopeRoute = ApiModelsScopeRouteImport.update({
  id: '/scope',
  path: '/scope',
  getParentRoute: () => ApiModelsRoute,
} as any)
const ApiSessionsIdRoute = ApiSessionsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiSessionsRoute,
} as any)
const ApiSkillsCheckRoute = ApiSkillsCheckRouteImport.update({
  id: '/check',
  path: '/check',
  getParentRoute: () => ApiSkillsRoute,
} as any)
const ApiSkillsInstallRoute = ApiSkillsInstallRouteImport.update({
  id: '/install',
  path: '/install',
  getParentRoute: () => ApiSkillsRoute,
} as any)
const ApiSkillsSearchRoute = ApiSkillsSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => ApiSkillsRoute,
} as any)
const ApiSkillsUpdateRoute = ApiSkillsUpdateRouteImport.update({
  id: '/update',
  path: '/update',
  getParentRoute: () => ApiSkillsRoute,
} as any)
const ApiAgentIdBashOutputRoute = ApiAgentIdBashOutputRouteImport.update({
  id: '/bash-output',
  path: '/bash-output',
  getParentRoute: () => ApiAgentIdRoute,
} as any)
const ApiAgentIdEventsRoute = ApiAgentIdEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => ApiAgentIdRoute,
} as any)
const ApiAgentIdSubagentsRoute = ApiAgentIdSubagentsRouteImport.update({
  id: '/subagents',
  path: '/subagents',
  getParentRoute: () => ApiAgentIdRoute,
} as any)
const ApiAgentRunningEventsRoute = ApiAgentRunningEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => ApiAgentRunningRoute,
} as any)
const ApiAuthApiKeyProviderRoute = ApiAuthApiKeyProviderRouteImport.update({
  id: '/api/auth/api-key/$provider',
  path: '/api/auth/api-key/$provider',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLoginProviderRoute = ApiAuthLoginProviderRouteImport.update({
  id: '/api/auth/login/$provider',
  path: '/api/auth/login/$provider',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLogoutProviderRoute = ApiAuthLogoutProviderRouteImport.update({
  id: '/api/auth/logout/$provider',
  path: '/api/auth/logout/$provider',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProvidersProviderUsageRoute =
  ApiProvidersProviderUsageRouteImport.update({
    id: '/api/providers/$provider/usage',
    path: '/api/providers/$provider/usage',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiSessionsIdAutoNameRoute = ApiSessionsIdAutoNameRouteImport.update({
  id: '/auto-name',
  path: '/auto-name',
  getParentRoute: () => ApiSessionsIdRoute,
} as any)
const ApiSessionsIdContextRoute = ApiSessionsIdContextRouteImport.update({
  id: '/context',
  path: '/context',
  getParentRoute: () => ApiSessionsIdRoute,
} as any)
const ApiSessionsIdExportRoute = ApiSessionsIdExportRouteImport.update({
  id: '/export',
  path: '/export',
  getParentRoute: () => ApiSessionsIdRoute,
} as any)
const ApiSessionsIdStateRoute = ApiSessionsIdStateRouteImport.update({
  id: '/state',
  path: '/state',
  getParentRoute: () => ApiSessionsIdRoute,
} as any)
const ApiSessionsIdEntriesEntryIdThinkingRoute =
  ApiSessionsIdEntriesEntryIdThinkingRouteImport.update({
    id: '/entries/$entryId/thinking',
    path: '/entries/$entryId/thinking',
    getParentRoute: () => ApiSessionsIdRoute,
  } as any)
const ApiSessionsIdEntriesEntryIdToolResultRoute =
  ApiSessionsIdEntriesEntryIdToolResultRouteImport.update({
    id: '/entries/$entryId/tool-result',
    path: '/entries/$entryId/tool-result',
    getParentRoute: () => ApiSessionsIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/agent-styles': typeof ApiAgentStylesRoute
  '/api/app-update': typeof ApiAppUpdateRoute
  '/api/cache-warming': typeof ApiCacheWarmingRoute
  '/api/default-cwd': typeof ApiDefaultCwdRoute
  '/api/file-index': typeof ApiFileIndexRoute
  '/api/home': typeof ApiHomeRoute
  '/api/image-resize': typeof ApiImageResizeRoute
  '/api/models': typeof ApiModelsRouteWithChildren
  '/api/models-config': typeof ApiModelsConfigRouteWithChildren
  '/api/plugins': typeof ApiPluginsRoute
  '/api/project-trust': typeof ApiProjectTrustRoute
  '/api/projects': typeof ApiProjectsRoute
  '/api/remote-access': typeof ApiRemoteAccessRoute
  '/api/sessions': typeof ApiSessionsRouteWithChildren
  '/api/skills': typeof ApiSkillsRouteWithChildren
  '/api/subagents': typeof ApiSubagentsRoute
  '/api/ui-locale': typeof ApiUiLocaleRoute
  '/api/worktrees': typeof ApiWorktreesRoute
  '/api/agent/$id': typeof ApiAgentIdRouteWithChildren
  '/api/agent/new': typeof ApiAgentNewRoute
  '/api/agent/running': typeof ApiAgentRunningRouteWithChildren
  '/api/auth/all-providers': typeof ApiAuthAllProvidersRoute
  '/api/auth/providers': typeof ApiAuthProvidersRoute
  '/api/cwd/browse': typeof ApiCwdBrowseRoute
  '/api/cwd/validate': typeof ApiCwdValidateRoute
  '/api/files/$': typeof ApiFilesSplatRoute
  '/api/git/diff': typeof ApiGitDiffRoute
  '/api/git/status': typeof ApiGitStatusRoute
  '/api/local/$': typeof ApiLocalSplatRoute
  '/api/models-config/catalog': typeof ApiModelsConfigCatalogRoute
  '/api/models-config/discover': typeof ApiModelsConfigDiscoverRoute
  '/api/models-config/test': typeof ApiModelsConfigTestRoute
  '/api/models/scope': typeof ApiModelsScopeRoute
  '/api/sessions/$id': typeof ApiSessionsIdRouteWithChildren
  '/api/skills/check': typeof ApiSkillsCheckRoute
  '/api/skills/install': typeof ApiSkillsInstallRoute
  '/api/skills/search': typeof ApiSkillsSearchRoute
  '/api/skills/update': typeof ApiSkillsUpdateRoute
  '/api/agent/$id/bash-output': typeof ApiAgentIdBashOutputRoute
  '/api/agent/$id/events': typeof ApiAgentIdEventsRoute
  '/api/agent/$id/subagents': typeof ApiAgentIdSubagentsRoute
  '/api/agent/running/events': typeof ApiAgentRunningEventsRoute
  '/api/auth/api-key/$provider': typeof ApiAuthApiKeyProviderRoute
  '/api/auth/login/$provider': typeof ApiAuthLoginProviderRoute
  '/api/auth/logout/$provider': typeof ApiAuthLogoutProviderRoute
  '/api/providers/$provider/usage': typeof ApiProvidersProviderUsageRoute
  '/api/sessions/$id/auto-name': typeof ApiSessionsIdAutoNameRoute
  '/api/sessions/$id/context': typeof ApiSessionsIdContextRoute
  '/api/sessions/$id/export': typeof ApiSessionsIdExportRoute
  '/api/sessions/$id/state': typeof ApiSessionsIdStateRoute
  '/api/sessions/$id/entries/$entryId/thinking': typeof ApiSessionsIdEntriesEntryIdThinkingRoute
  '/api/sessions/$id/entries/$entryId/tool-result': typeof ApiSessionsIdEntriesEntryIdToolResultRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/agent-styles': typeof ApiAgentStylesRoute
  '/api/app-update': typeof ApiAppUpdateRoute
  '/api/cache-warming': typeof ApiCacheWarmingRoute
  '/api/default-cwd': typeof ApiDefaultCwdRoute
  '/api/file-index': typeof ApiFileIndexRoute
  '/api/home': typeof ApiHomeRoute
  '/api/image-resize': typeof ApiImageResizeRoute
  '/api/models': typeof ApiModelsRouteWithChildren
  '/api/models-config': typeof ApiModelsConfigRouteWithChildren
  '/api/plugins': typeof ApiPluginsRoute
  '/api/project-trust': typeof ApiProjectTrustRoute
  '/api/projects': typeof ApiProjectsRoute
  '/api/remote-access': typeof ApiRemoteAccessRoute
  '/api/sessions': typeof ApiSessionsRouteWithChildren
  '/api/skills': typeof ApiSkillsRouteWithChildren
  '/api/subagents': typeof ApiSubagentsRoute
  '/api/ui-locale': typeof ApiUiLocaleRoute
  '/api/worktrees': typeof ApiWorktreesRoute
  '/api/agent/$id': typeof ApiAgentIdRouteWithChildren
  '/api/agent/new': typeof ApiAgentNewRoute
  '/api/agent/running': typeof ApiAgentRunningRouteWithChildren
  '/api/auth/all-providers': typeof ApiAuthAllProvidersRoute
  '/api/auth/providers': typeof ApiAuthProvidersRoute
  '/api/cwd/browse': typeof ApiCwdBrowseRoute
  '/api/cwd/validate': typeof ApiCwdValidateRoute
  '/api/files/$': typeof ApiFilesSplatRoute
  '/api/git/diff': typeof ApiGitDiffRoute
  '/api/git/status': typeof ApiGitStatusRoute
  '/api/local/$': typeof ApiLocalSplatRoute
  '/api/models-config/catalog': typeof ApiModelsConfigCatalogRoute
  '/api/models-config/discover': typeof ApiModelsConfigDiscoverRoute
  '/api/models-config/test': typeof ApiModelsConfigTestRoute
  '/api/models/scope': typeof ApiModelsScopeRoute
  '/api/sessions/$id': typeof ApiSessionsIdRouteWithChildren
  '/api/skills/check': typeof ApiSkillsCheckRoute
  '/api/skills/install': typeof ApiSkillsInstallRoute
  '/api/skills/search': typeof ApiSkillsSearchRoute
  '/api/skills/update': typeof ApiSkillsUpdateRoute
  '/api/agent/$id/bash-output': typeof ApiAgentIdBashOutputRoute
  '/api/agent/$id/events': typeof ApiAgentIdEventsRoute
  '/api/agent/$id/subagents': typeof ApiAgentIdSubagentsRoute
  '/api/agent/running/events': typeof ApiAgentRunningEventsRoute
  '/api/auth/api-key/$provider': typeof ApiAuthApiKeyProviderRoute
  '/api/auth/login/$provider': typeof ApiAuthLoginProviderRoute
  '/api/auth/logout/$provider': typeof ApiAuthLogoutProviderRoute
  '/api/providers/$provider/usage': typeof ApiProvidersProviderUsageRoute
  '/api/sessions/$id/auto-name': typeof ApiSessionsIdAutoNameRoute
  '/api/sessions/$id/context': typeof ApiSessionsIdContextRoute
  '/api/sessions/$id/export': typeof ApiSessionsIdExportRoute
  '/api/sessions/$id/state': typeof ApiSessionsIdStateRoute
  '/api/sessions/$id/entries/$entryId/thinking': typeof ApiSessionsIdEntriesEntryIdThinkingRoute
  '/api/sessions/$id/entries/$entryId/tool-result': typeof ApiSessionsIdEntriesEntryIdToolResultRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/agent-styles': typeof ApiAgentStylesRoute
  '/api/app-update': typeof ApiAppUpdateRoute
  '/api/cache-warming': typeof ApiCacheWarmingRoute
  '/api/default-cwd': typeof ApiDefaultCwdRoute
  '/api/file-index': typeof ApiFileIndexRoute
  '/api/home': typeof ApiHomeRoute
  '/api/image-resize': typeof ApiImageResizeRoute
  '/api/models': typeof ApiModelsRouteWithChildren
  '/api/models-config': typeof ApiModelsConfigRouteWithChildren
  '/api/plugins': typeof ApiPluginsRoute
  '/api/project-trust': typeof ApiProjectTrustRoute
  '/api/projects': typeof ApiProjectsRoute
  '/api/remote-access': typeof ApiRemoteAccessRoute
  '/api/sessions': typeof ApiSessionsRouteWithChildren
  '/api/skills': typeof ApiSkillsRouteWithChildren
  '/api/subagents': typeof ApiSubagentsRoute
  '/api/ui-locale': typeof ApiUiLocaleRoute
  '/api/worktrees': typeof ApiWorktreesRoute
  '/api/agent/$id': typeof ApiAgentIdRouteWithChildren
  '/api/agent/new': typeof ApiAgentNewRoute
  '/api/agent/running': typeof ApiAgentRunningRouteWithChildren
  '/api/auth/all-providers': typeof ApiAuthAllProvidersRoute
  '/api/auth/providers': typeof ApiAuthProvidersRoute
  '/api/cwd/browse': typeof ApiCwdBrowseRoute
  '/api/cwd/validate': typeof ApiCwdValidateRoute
  '/api/files/$': typeof ApiFilesSplatRoute
  '/api/git/diff': typeof ApiGitDiffRoute
  '/api/git/status': typeof ApiGitStatusRoute
  '/api/local/$': typeof ApiLocalSplatRoute
  '/api/models-config/catalog': typeof ApiModelsConfigCatalogRoute
  '/api/models-config/discover': typeof ApiModelsConfigDiscoverRoute
  '/api/models-config/test': typeof ApiModelsConfigTestRoute
  '/api/models/scope': typeof ApiModelsScopeRoute
  '/api/sessions/$id': typeof ApiSessionsIdRouteWithChildren
  '/api/skills/check': typeof ApiSkillsCheckRoute
  '/api/skills/install': typeof ApiSkillsInstallRoute
  '/api/skills/search': typeof ApiSkillsSearchRoute
  '/api/skills/update': typeof ApiSkillsUpdateRoute
  '/api/agent/$id/bash-output': typeof ApiAgentIdBashOutputRoute
  '/api/agent/$id/events': typeof ApiAgentIdEventsRoute
  '/api/agent/$id/subagents': typeof ApiAgentIdSubagentsRoute
  '/api/agent/running/events': typeof ApiAgentRunningEventsRoute
  '/api/auth/api-key/$provider': typeof ApiAuthApiKeyProviderRoute
  '/api/auth/login/$provider': typeof ApiAuthLoginProviderRoute
  '/api/auth/logout/$provider': typeof ApiAuthLogoutProviderRoute
  '/api/providers/$provider/usage': typeof ApiProvidersProviderUsageRoute
  '/api/sessions/$id/auto-name': typeof ApiSessionsIdAutoNameRoute
  '/api/sessions/$id/context': typeof ApiSessionsIdContextRoute
  '/api/sessions/$id/export': typeof ApiSessionsIdExportRoute
  '/api/sessions/$id/state': typeof ApiSessionsIdStateRoute
  '/api/sessions/$id/entries/$entryId/thinking': typeof ApiSessionsIdEntriesEntryIdThinkingRoute
  '/api/sessions/$id/entries/$entryId/tool-result': typeof ApiSessionsIdEntriesEntryIdToolResultRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/agent-styles'
    | '/api/app-update'
    | '/api/cache-warming'
    | '/api/default-cwd'
    | '/api/file-index'
    | '/api/home'
    | '/api/image-resize'
    | '/api/models'
    | '/api/models-config'
    | '/api/plugins'
    | '/api/project-trust'
    | '/api/projects'
    | '/api/remote-access'
    | '/api/sessions'
    | '/api/skills'
    | '/api/subagents'
    | '/api/ui-locale'
    | '/api/worktrees'
    | '/api/agent/$id'
    | '/api/agent/new'
    | '/api/agent/running'
    | '/api/auth/all-providers'
    | '/api/auth/providers'
    | '/api/cwd/browse'
    | '/api/cwd/validate'
    | '/api/files/$'
    | '/api/git/diff'
    | '/api/git/status'
    | '/api/local/$'
    | '/api/models-config/catalog'
    | '/api/models-config/discover'
    | '/api/models-config/test'
    | '/api/models/scope'
    | '/api/sessions/$id'
    | '/api/skills/check'
    | '/api/skills/install'
    | '/api/skills/search'
    | '/api/skills/update'
    | '/api/agent/$id/bash-output'
    | '/api/agent/$id/events'
    | '/api/agent/$id/subagents'
    | '/api/agent/running/events'
    | '/api/auth/api-key/$provider'
    | '/api/auth/login/$provider'
    | '/api/auth/logout/$provider'
    | '/api/providers/$provider/usage'
    | '/api/sessions/$id/auto-name'
    | '/api/sessions/$id/context'
    | '/api/sessions/$id/export'
    | '/api/sessions/$id/state'
    | '/api/sessions/$id/entries/$entryId/thinking'
    | '/api/sessions/$id/entries/$entryId/tool-result'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/agent-styles'
    | '/api/app-update'
    | '/api/cache-warming'
    | '/api/default-cwd'
    | '/api/file-index'
    | '/api/home'
    | '/api/image-resize'
    | '/api/models'
    | '/api/models-config'
    | '/api/plugins'
    | '/api/project-trust'
    | '/api/projects'
    | '/api/remote-access'
    | '/api/sessions'
    | '/api/skills'
    | '/api/subagents'
    | '/api/ui-locale'
    | '/api/worktrees'
    | '/api/agent/$id'
    | '/api/agent/new'
    | '/api/agent/running'
    | '/api/auth/all-providers'
    | '/api/auth/providers'
    | '/api/cwd/browse'
    | '/api/cwd/validate'
    | '/api/files/$'
    | '/api/git/diff'
    | '/api/git/status'
    | '/api/local/$'
    | '/api/models-config/catalog'
    | '/api/models-config/discover'
    | '/api/models-config/test'
    | '/api/models/scope'
    | '/api/sessions/$id'
    | '/api/skills/check'
    | '/api/skills/install'
    | '/api/skills/search'
    | '/api/skills/update'
    | '/api/agent/$id/bash-output'
    | '/api/agent/$id/events'
    | '/api/agent/$id/subagents'
    | '/api/agent/running/events'
    | '/api/auth/api-key/$provider'
    | '/api/auth/login/$provider'
    | '/api/auth/logout/$provider'
    | '/api/providers/$provider/usage'
    | '/api/sessions/$id/auto-name'
    | '/api/sessions/$id/context'
    | '/api/sessions/$id/export'
    | '/api/sessions/$id/state'
    | '/api/sessions/$id/entries/$entryId/thinking'
    | '/api/sessions/$id/entries/$entryId/tool-result'
  id:
    | '__root__'
    | '/'
    | '/api/agent-styles'
    | '/api/app-update'
    | '/api/cache-warming'
    | '/api/default-cwd'
    | '/api/file-index'
    | '/api/home'
    | '/api/image-resize'
    | '/api/models'
    | '/api/models-config'
    | '/api/plugins'
    | '/api/project-trust'
    | '/api/projects'
    | '/api/remote-access'
    | '/api/sessions'
    | '/api/skills'
    | '/api/subagents'
    | '/api/ui-locale'
    | '/api/worktrees'
    | '/api/agent/$id'
    | '/api/agent/new'
    | '/api/agent/running'
    | '/api/auth/all-providers'
    | '/api/auth/providers'
    | '/api/cwd/browse'
    | '/api/cwd/validate'
    | '/api/files/$'
    | '/api/git/diff'
    | '/api/git/status'
    | '/api/local/$'
    | '/api/models-config/catalog'
    | '/api/models-config/discover'
    | '/api/models-config/test'
    | '/api/models/scope'
    | '/api/sessions/$id'
    | '/api/skills/check'
    | '/api/skills/install'
    | '/api/skills/search'
    | '/api/skills/update'
    | '/api/agent/$id/bash-output'
    | '/api/agent/$id/events'
    | '/api/agent/$id/subagents'
    | '/api/agent/running/events'
    | '/api/auth/api-key/$provider'
    | '/api/auth/login/$provider'
    | '/api/auth/logout/$provider'
    | '/api/providers/$provider/usage'
    | '/api/sessions/$id/auto-name'
    | '/api/sessions/$id/context'
    | '/api/sessions/$id/export'
    | '/api/sessions/$id/state'
    | '/api/sessions/$id/entries/$entryId/thinking'
    | '/api/sessions/$id/entries/$entryId/tool-result'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiAgentStylesRoute: typeof ApiAgentStylesRoute
  ApiAppUpdateRoute: typeof ApiAppUpdateRoute
  ApiCacheWarmingRoute: typeof ApiCacheWarmingRoute
  ApiDefaultCwdRoute: typeof ApiDefaultCwdRoute
  ApiFileIndexRoute: typeof ApiFileIndexRoute
  ApiHomeRoute: typeof ApiHomeRoute
  ApiImageResizeRoute: typeof ApiImageResizeRoute
  ApiModelsRoute: typeof ApiModelsRouteWithChildren
  ApiModelsConfigRoute: typeof ApiModelsConfigRouteWithChildren
  ApiPluginsRoute: typeof ApiPluginsRoute
  ApiProjectTrustRoute: typeof ApiProjectTrustRoute
  ApiProjectsRoute: typeof ApiProjectsRoute
  ApiRemoteAccessRoute: typeof ApiRemoteAccessRoute
  ApiSessionsRoute: typeof ApiSessionsRouteWithChildren
  ApiSkillsRoute: typeof ApiSkillsRouteWithChildren
  ApiSubagentsRoute: typeof ApiSubagentsRoute
  ApiUiLocaleRoute: typeof ApiUiLocaleRoute
  ApiWorktreesRoute: typeof ApiWorktreesRoute
  ApiAgentIdRoute: typeof ApiAgentIdRouteWithChildren
  ApiAgentNewRoute: typeof ApiAgentNewRoute
  ApiAgentRunningRoute: typeof ApiAgentRunningRouteWithChildren
  ApiAuthAllProvidersRoute: typeof ApiAuthAllProvidersRoute
  ApiAuthProvidersRoute: typeof ApiAuthProvidersRoute
  ApiCwdBrowseRoute: typeof ApiCwdBrowseRoute
  ApiCwdValidateRoute: typeof ApiCwdValidateRoute
  ApiFilesSplatRoute: typeof ApiFilesSplatRoute
  ApiGitDiffRoute: typeof ApiGitDiffRoute
  ApiGitStatusRoute: typeof ApiGitStatusRoute
  ApiLocalSplatRoute: typeof ApiLocalSplatRoute
  ApiAuthApiKeyProviderRoute: typeof ApiAuthApiKeyProviderRoute
  ApiAuthLoginProviderRoute: typeof ApiAuthLoginProviderRoute
  ApiAuthLogoutProviderRoute: typeof ApiAuthLogoutProviderRoute
  ApiProvidersProviderUsageRoute: typeof ApiProvidersProviderUsageRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agent-styles': {
      id: '/api/agent-styles'
      path: '/api/agent-styles'
      fullPath: '/api/agent-styles'
      preLoaderRoute: typeof ApiAgentStylesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/app-update': {
      id: '/api/app-update'
      path: '/api/app-update'
      fullPath: '/api/app-update'
      preLoaderRoute: typeof ApiAppUpdateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cache-warming': {
      id: '/api/cache-warming'
      path: '/api/cache-warming'
      fullPath: '/api/cache-warming'
      preLoaderRoute: typeof ApiCacheWarmingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/default-cwd': {
      id: '/api/default-cwd'
      path: '/api/default-cwd'
      fullPath: '/api/default-cwd'
      preLoaderRoute: typeof ApiDefaultCwdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/file-index': {
      id: '/api/file-index'
      path: '/api/file-index'
      fullPath: '/api/file-index'
      preLoaderRoute: typeof ApiFileIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/home': {
      id: '/api/home'
      path: '/api/home'
      fullPath: '/api/home'
      preLoaderRoute: typeof ApiHomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/image-resize': {
      id: '/api/image-resize'
      path: '/api/image-resize'
      fullPath: '/api/image-resize'
      preLoaderRoute: typeof ApiImageResizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/models': {
      id: '/api/models'
      path: '/api/models'
      fullPath: '/api/models'
      preLoaderRoute: typeof ApiModelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/models-config': {
      id: '/api/models-config'
      path: '/api/models-config'
      fullPath: '/api/models-config'
      preLoaderRoute: typeof ApiModelsConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/plugins': {
      id: '/api/plugins'
      path: '/api/plugins'
      fullPath: '/api/plugins'
      preLoaderRoute: typeof ApiPluginsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/project-trust': {
      id: '/api/project-trust'
      path: '/api/project-trust'
      fullPath: '/api/project-trust'
      preLoaderRoute: typeof ApiProjectTrustRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/projects': {
      id: '/api/projects'
      path: '/api/projects'
      fullPath: '/api/projects'
      preLoaderRoute: typeof ApiProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/remote-access': {
      id: '/api/remote-access'
      path: '/api/remote-access'
      fullPath: '/api/remote-access'
      preLoaderRoute: typeof ApiRemoteAccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sessions': {
      id: '/api/sessions'
      path: '/api/sessions'
      fullPath: '/api/sessions'
      preLoaderRoute: typeof ApiSessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/skills': {
      id: '/api/skills'
      path: '/api/skills'
      fullPath: '/api/skills'
      preLoaderRoute: typeof ApiSkillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/subagents': {
      id: '/api/subagents'
      path: '/api/subagents'
      fullPath: '/api/subagents'
      preLoaderRoute: typeof ApiSubagentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ui-locale': {
      id: '/api/ui-locale'
      path: '/api/ui-locale'
      fullPath: '/api/ui-locale'
      preLoaderRoute: typeof ApiUiLocaleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/worktrees': {
      id: '/api/worktrees'
      path: '/api/worktrees'
      fullPath: '/api/worktrees'
      preLoaderRoute: typeof ApiWorktreesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agent/$id': {
      id: '/api/agent/$id'
      path: '/api/agent/$id'
      fullPath: '/api/agent/$id'
      preLoaderRoute: typeof ApiAgentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agent/new': {
      id: '/api/agent/new'
      path: '/api/agent/new'
      fullPath: '/api/agent/new'
      preLoaderRoute: typeof ApiAgentNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agent/running': {
      id: '/api/agent/running'
      path: '/api/agent/running'
      fullPath: '/api/agent/running'
      preLoaderRoute: typeof ApiAgentRunningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/all-providers': {
      id: '/api/auth/all-providers'
      path: '/api/auth/all-providers'
      fullPath: '/api/auth/all-providers'
      preLoaderRoute: typeof ApiAuthAllProvidersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/providers': {
      id: '/api/auth/providers'
      path: '/api/auth/providers'
      fullPath: '/api/auth/providers'
      preLoaderRoute: typeof ApiAuthProvidersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cwd/browse': {
      id: '/api/cwd/browse'
      path: '/api/cwd/browse'
      fullPath: '/api/cwd/browse'
      preLoaderRoute: typeof ApiCwdBrowseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cwd/validate': {
      id: '/api/cwd/validate'
      path: '/api/cwd/validate'
      fullPath: '/api/cwd/validate'
      preLoaderRoute: typeof ApiCwdValidateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/files/$': {
      id: '/api/files/$'
      path: '/api/files/$'
      fullPath: '/api/files/$'
      preLoaderRoute: typeof ApiFilesSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/git/diff': {
      id: '/api/git/diff'
      path: '/api/git/diff'
      fullPath: '/api/git/diff'
      preLoaderRoute: typeof ApiGitDiffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/git/status': {
      id: '/api/git/status'
      path: '/api/git/status'
      fullPath: '/api/git/status'
      preLoaderRoute: typeof ApiGitStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/local/$': {
      id: '/api/local/$'
      path: '/api/local/$'
      fullPath: '/api/local/$'
      preLoaderRoute: typeof ApiLocalSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/models-config/catalog': {
      id: '/api/models-config/catalog'
      path: '/catalog'
      fullPath: '/api/models-config/catalog'
      preLoaderRoute: typeof ApiModelsConfigCatalogRouteImport
      parentRoute: typeof ApiModelsConfigRoute
    }
    '/api/models-config/discover': {
      id: '/api/models-config/discover'
      path: '/discover'
      fullPath: '/api/models-config/discover'
      preLoaderRoute: typeof ApiModelsConfigDiscoverRouteImport
      parentRoute: typeof ApiModelsConfigRoute
    }
    '/api/models-config/test': {
      id: '/api/models-config/test'
      path: '/test'
      fullPath: '/api/models-config/test'
      preLoaderRoute: typeof ApiModelsConfigTestRouteImport
      parentRoute: typeof ApiModelsConfigRoute
    }
    '/api/models/scope': {
      id: '/api/models/scope'
      path: '/scope'
      fullPath: '/api/models/scope'
      preLoaderRoute: typeof ApiModelsScopeRouteImport
      parentRoute: typeof ApiModelsRoute
    }
    '/api/sessions/$id': {
      id: '/api/sessions/$id'
      path: '/$id'
      fullPath: '/api/sessions/$id'
      preLoaderRoute: typeof ApiSessionsIdRouteImport
      parentRoute: typeof ApiSessionsRoute
    }
    '/api/skills/check': {
      id: '/api/skills/check'
      path: '/check'
      fullPath: '/api/skills/check'
      preLoaderRoute: typeof ApiSkillsCheckRouteImport
      parentRoute: typeof ApiSkillsRoute
    }
    '/api/skills/install': {
      id: '/api/skills/install'
      path: '/install'
      fullPath: '/api/skills/install'
      preLoaderRoute: typeof ApiSkillsInstallRouteImport
      parentRoute: typeof ApiSkillsRoute
    }
    '/api/skills/search': {
      id: '/api/skills/search'
      path: '/search'
      fullPath: '/api/skills/search'
      preLoaderRoute: typeof ApiSkillsSearchRouteImport
      parentRoute: typeof ApiSkillsRoute
    }
    '/api/skills/update': {
      id: '/api/skills/update'
      path: '/update'
      fullPath: '/api/skills/update'
      preLoaderRoute: typeof ApiSkillsUpdateRouteImport
      parentRoute: typeof ApiSkillsRoute
    }
    '/api/agent/$id/bash-output': {
      id: '/api/agent/$id/bash-output'
      path: '/bash-output'
      fullPath: '/api/agent/$id/bash-output'
      preLoaderRoute: typeof ApiAgentIdBashOutputRouteImport
      parentRoute: typeof ApiAgentIdRoute
    }
    '/api/agent/$id/events': {
      id: '/api/agent/$id/events'
      path: '/events'
      fullPath: '/api/agent/$id/events'
      preLoaderRoute: typeof ApiAgentIdEventsRouteImport
      parentRoute: typeof ApiAgentIdRoute
    }
    '/api/agent/$id/subagents': {
      id: '/api/agent/$id/subagents'
      path: '/subagents'
      fullPath: '/api/agent/$id/subagents'
      preLoaderRoute: typeof ApiAgentIdSubagentsRouteImport
      parentRoute: typeof ApiAgentIdRoute
    }
    '/api/agent/running/events': {
      id: '/api/agent/running/events'
      path: '/events'
      fullPath: '/api/agent/running/events'
      preLoaderRoute: typeof ApiAgentRunningEventsRouteImport
      parentRoute: typeof ApiAgentRunningRoute
    }
    '/api/auth/api-key/$provider': {
      id: '/api/auth/api-key/$provider'
      path: '/api/auth/api-key/$provider'
      fullPath: '/api/auth/api-key/$provider'
      preLoaderRoute: typeof ApiAuthApiKeyProviderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/login/$provider': {
      id: '/api/auth/login/$provider'
      path: '/api/auth/login/$provider'
      fullPath: '/api/auth/login/$provider'
      preLoaderRoute: typeof ApiAuthLoginProviderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/logout/$provider': {
      id: '/api/auth/logout/$provider'
      path: '/api/auth/logout/$provider'
      fullPath: '/api/auth/logout/$provider'
      preLoaderRoute: typeof ApiAuthLogoutProviderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/providers/$provider/usage': {
      id: '/api/providers/$provider/usage'
      path: '/api/providers/$provider/usage'
      fullPath: '/api/providers/$provider/usage'
      preLoaderRoute: typeof ApiProvidersProviderUsageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sessions/$id/auto-name': {
      id: '/api/sessions/$id/auto-name'
      path: '/auto-name'
      fullPath: '/api/sessions/$id/auto-name'
      preLoaderRoute: typeof ApiSessionsIdAutoNameRouteImport
      parentRoute: typeof ApiSessionsIdRoute
    }
    '/api/sessions/$id/context': {
      id: '/api/sessions/$id/context'
      path: '/context'
      fullPath: '/api/sessions/$id/context'
      preLoaderRoute: typeof ApiSessionsIdContextRouteImport
      parentRoute: typeof ApiSessionsIdRoute
    }
    '/api/sessions/$id/export': {
      id: '/api/sessions/$id/export'
      path: '/export'
      fullPath: '/api/sessions/$id/export'
      preLoaderRoute: typeof ApiSessionsIdExportRouteImport
      parentRoute: typeof ApiSessionsIdRoute
    }
    '/api/sessions/$id/state': {
      id: '/api/sessions/$id/state'
      path: '/state'
      fullPath: '/api/sessions/$id/state'
      preLoaderRoute: typeof ApiSessionsIdStateRouteImport
      parentRoute: typeof ApiSessionsIdRoute
    }
    '/api/sessions/$id/entries/$entryId/thinking': {
      id: '/api/sessions/$id/entries/$entryId/thinking'
      path: '/entries/$entryId/thinking'
      fullPath: '/api/sessions/$id/entries/$entryId/thinking'
      preLoaderRoute: typeof ApiSessionsIdEntriesEntryIdThinkingRouteImport
      parentRoute: typeof ApiSessionsIdRoute
    }
    '/api/sessions/$id/entries/$entryId/tool-result': {
      id: '/api/sessions/$id/entries/$entryId/tool-result'
      path: '/entries/$entryId/tool-result'
      fullPath: '/api/sessions/$id/entries/$entryId/tool-result'
      preLoaderRoute: typeof ApiSessionsIdEntriesEntryIdToolResultRouteImport
      parentRoute: typeof ApiSessionsIdRoute
    }
  }
}

interface ApiModelsRouteChildren {
  ApiModelsScopeRoute: typeof ApiModelsScopeRoute
}

const ApiModelsRouteChildren: ApiModelsRouteChildren = {
  ApiModelsScopeRoute: ApiModelsScopeRoute,
}

const ApiModelsRouteWithChildren = ApiModelsRoute._addFileChildren(
  ApiModelsRouteChildren,
)

interface ApiModelsConfigRouteChildren {
  ApiModelsConfigCatalogRoute: typeof ApiModelsConfigCatalogRoute
  ApiModelsConfigDiscoverRoute: typeof ApiModelsConfigDiscoverRoute
  ApiModelsConfigTestRoute: typeof ApiModelsConfigTestRoute
}

const ApiModelsConfigRouteChildren: ApiModelsConfigRouteChildren = {
  ApiModelsConfigCatalogRoute: ApiModelsConfigCatalogRoute,
  ApiModelsConfigDiscoverRoute: ApiModelsConfigDiscoverRoute,
  ApiModelsConfigTestRoute: ApiModelsConfigTestRoute,
}

const ApiModelsConfigRouteWithChildren = ApiModelsConfigRoute._addFileChildren(
  ApiModelsConfigRouteChildren,
)

interface ApiSessionsIdRouteChildren {
  ApiSessionsIdAutoNameRoute: typeof ApiSessionsIdAutoNameRoute
  ApiSessionsIdContextRoute: typeof ApiSessionsIdContextRoute
  ApiSessionsIdExportRoute: typeof ApiSessionsIdExportRoute
  ApiSessionsIdStateRoute: typeof ApiSessionsIdStateRoute
  ApiSessionsIdEntriesEntryIdThinkingRoute: typeof ApiSessionsIdEntriesEntryIdThinkingRoute
  ApiSessionsIdEntriesEntryIdToolResultRoute: typeof ApiSessionsIdEntriesEntryIdToolResultRoute
}

const ApiSessionsIdRouteChildren: ApiSessionsIdRouteChildren = {
  ApiSessionsIdAutoNameRoute: ApiSessionsIdAutoNameRoute,
  ApiSessionsIdContextRoute: ApiSessionsIdContextRoute,
  ApiSessionsIdExportRoute: ApiSessionsIdExportRoute,
  ApiSessionsIdStateRoute: ApiSessionsIdStateRoute,
  ApiSessionsIdEntriesEntryIdThinkingRoute:
    ApiSessionsIdEntriesEntryIdThinkingRoute,
  ApiSessionsIdEntriesEntryIdToolResultRoute:
    ApiSessionsIdEntriesEntryIdToolResultRoute,
}

const ApiSessionsIdRouteWithChildren = ApiSessionsIdRoute._addFileChildren(
  ApiSessionsIdRouteChildren,
)

interface ApiSessionsRouteChildren {
  ApiSessionsIdRoute: typeof ApiSessionsIdRouteWithChildren
}

const ApiSessionsRouteChildren: ApiSessionsRouteChildren = {
  ApiSessionsIdRoute: ApiSessionsIdRouteWithChildren,
}

const ApiSessionsRouteWithChildren = ApiSessionsRoute._addFileChildren(
  ApiSessionsRouteChildren,
)

interface ApiSkillsRouteChildren {
  ApiSkillsCheckRoute: typeof ApiSkillsCheckRoute
  ApiSkillsInstallRoute: typeof ApiSkillsInstallRoute
  ApiSkillsSearchRoute: typeof ApiSkillsSearchRoute
  ApiSkillsUpdateRoute: typeof ApiSkillsUpdateRoute
}

const ApiSkillsRouteChildren: ApiSkillsRouteChildren = {
  ApiSkillsCheckRoute: ApiSkillsCheckRoute,
  ApiSkillsInstallRoute: ApiSkillsInstallRoute,
  ApiSkillsSearchRoute: ApiSkillsSearchRoute,
  ApiSkillsUpdateRoute: ApiSkillsUpdateRoute,
}

const ApiSkillsRouteWithChildren = ApiSkillsRoute._addFileChildren(
  ApiSkillsRouteChildren,
)

interface ApiAgentIdRouteChildren {
  ApiAgentIdBashOutputRoute: typeof ApiAgentIdBashOutputRoute
  ApiAgentIdEventsRoute: typeof ApiAgentIdEventsRoute
  ApiAgentIdSubagentsRoute: typeof ApiAgentIdSubagentsRoute
}

const ApiAgentIdRouteChildren: ApiAgentIdRouteChildren = {
  ApiAgentIdBashOutputRoute: ApiAgentIdBashOutputRoute,
  ApiAgentIdEventsRoute: ApiAgentIdEventsRoute,
  ApiAgentIdSubagentsRoute: ApiAgentIdSubagentsRoute,
}

const ApiAgentIdRouteWithChildren = ApiAgentIdRoute._addFileChildren(
  ApiAgentIdRouteChildren,
)

interface ApiAgentRunningRouteChildren {
  ApiAgentRunningEventsRoute: typeof ApiAgentRunningEventsRoute
}

const ApiAgentRunningRouteChildren: ApiAgentRunningRouteChildren = {
  ApiAgentRunningEventsRoute: ApiAgentRunningEventsRoute,
}

const ApiAgentRunningRouteWithChildren = ApiAgentRunningRoute._addFileChildren(
  ApiAgentRunningRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiAgentStylesRoute: ApiAgentStylesRoute,
  ApiAppUpdateRoute: ApiAppUpdateRoute,
  ApiCacheWarmingRoute: ApiCacheWarmingRoute,
  ApiDefaultCwdRoute: ApiDefaultCwdRoute,
  ApiFileIndexRoute: ApiFileIndexRoute,
  ApiHomeRoute: ApiHomeRoute,
  ApiImageResizeRoute: ApiImageResizeRoute,
  ApiModelsRoute: ApiModelsRouteWithChildren,
  ApiModelsConfigRoute: ApiModelsConfigRouteWithChildren,
  ApiPluginsRoute: ApiPluginsRoute,
  ApiProjectTrustRoute: ApiProjectTrustRoute,
  ApiProjectsRoute: ApiProjectsRoute,
  ApiRemoteAccessRoute: ApiRemoteAccessRoute,
  ApiSessionsRoute: ApiSessionsRouteWithChildren,
  ApiSkillsRoute: ApiSkillsRouteWithChildren,
  ApiSubagentsRoute: ApiSubagentsRoute,
  ApiUiLocaleRoute: ApiUiLocaleRoute,
  ApiWorktreesRoute: ApiWorktreesRoute,
  ApiAgentIdRoute: ApiAgentIdRouteWithChildren,
  ApiAgentNewRoute: ApiAgentNewRoute,
  ApiAgentRunningRoute: ApiAgentRunningRouteWithChildren,
  ApiAuthAllProvidersRoute: ApiAuthAllProvidersRoute,
  ApiAuthProvidersRoute: ApiAuthProvidersRoute,
  ApiCwdBrowseRoute: ApiCwdBrowseRoute,
  ApiCwdValidateRoute: ApiCwdValidateRoute,
  ApiFilesSplatRoute: ApiFilesSplatRoute,
  ApiGitDiffRoute: ApiGitDiffRoute,
  ApiGitStatusRoute: ApiGitStatusRoute,
  ApiLocalSplatRoute: ApiLocalSplatRoute,
  ApiAuthApiKeyProviderRoute: ApiAuthApiKeyProviderRoute,
  ApiAuthLoginProviderRoute: ApiAuthLoginProviderRoute,
  ApiAuthLogoutProviderRoute: ApiAuthLogoutProviderRoute,
  ApiProvidersProviderUsageRoute: ApiProvidersProviderUsageRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
